import type { DeliveryClientSchema } from "../../../../lib/models/core.models.js";
import type { ItemsFeedPayload } from "../../../../lib/queries/content-items/models/content-item.models.js";

export default {
	items: [
		{
			system: {
				id: "d56bff34-5ce8-4ac1-9cb8-547848b3a22b",
				name: "Al Pacino",
				codename: "al_pacino",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:25.6499619Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Al",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Pacino",
				},
			},
		},
		{
			system: {
				id: "b25e6ed1-0a3f-4975-bb84-4c7efefa70d0",
				name: "Amy Adams",
				codename: "amy_adams",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:17.8650469Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Amy",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Adams",
				},
			},
		},
		{
			system: {
				id: "114f4d17-936f-406d-8e59-e34c7eb5f200",
				name: "Ana de Armas",
				codename: "ana_de_armas",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:05.6615288Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Ana",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "de Armas",
				},
			},
		},
		{
			system: {
				id: "19f8dbfa-46d8-4f0d-9afa-c88dc963ff96",
				name: "Angelina Jolie",
				codename: "angelina_jolie",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:16.1359703Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Angelina",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Jolie",
				},
			},
		},
		{
			system: {
				id: "a0f01bd5-c1d1-4aad-92de-89e7835b561e",
				name: "Anne Hathaway",
				codename: "anne_hathaway",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:51.1280388Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Anne",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Hathaway",
				},
			},
		},
		{
			system: {
				id: "68bc6cea-79ba-4748-92d8-fdbf33bd55ea",
				name: "Anthony Hopkins",
				codename: "anthony_hopkins",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:00.3600159Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Anthony",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Hopkins",
				},
			},
		},
		{
			system: {
				id: "a7c0313e-0bb0-4dc3-9d5b-61f9f5757b5e",
				name: "Antonio Banderas",
				codename: "antonio_banderas",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:06.8102193Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Antonio",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Banderas",
				},
			},
		},
		{
			system: {
				id: "f87989d8-ac15-4b87-b43a-37d85e0002f6",
				name: "Avengers: Endgame",
				codename: "avengers__endgame",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:39.8815857Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Avengers: Endgame",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 181,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>After the devastating events of Avengers: Infinity War, the remaining Avengers assemble one final time to undo Thanos' destruction and restore the universe. The epic conclusion to the Infinity Saga.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2019-04-26T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Action",
							codename: "action",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "avengers-endgame",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "The highest-grossing film of all time upon release, Avengers: Endgame is the culmination of 22 Marvel Cinematic Universe films.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["chris_evans", "scarlett_johansson", "robert_downey_jr_", "jeremy_renner"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "0f33b050-4cf3-41f4-9a9d-33bd1c7ba5ef",
				name: "Benedict Cumberbatch",
				codename: "benedict_cumberbatch",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:06.8688409Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Benedict",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Cumberbatch",
				},
			},
		},
		{
			system: {
				id: "292468fe-ac5a-4505-b6f1-83cbbee89687",
				name: "Black Panther",
				codename: "black_panther",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:53.6784162Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Black Panther",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 134,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>T'Challa returns home to the African nation of Wakanda to take his rightful place as king. When a powerful enemy with ties to his past threatens to destroy the country, he must rally his allies and release the full power of the Black Panther.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2018-02-16T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Action",
							codename: "action",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "black-panther",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Marvel's Black Panther became a cultural phenomenon and was nominated for 7 Academy Awards including Best Picture.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["chadwick_boseman", "lupita_nyong_o"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "d7862a9a-0333-491c-9db9-ee91a7828a84",
				name: "Brad Pitt",
				codename: "brad_pitt",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:15.7816154Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Brad",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Pitt",
				},
			},
		},
		{
			system: {
				id: "5d096ac1-fc8c-4275-b411-11a1de4b1fbf",
				name: "Brie Larson",
				codename: "brie_larson",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:15.552657Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Brie",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Larson",
				},
			},
		},
		{
			system: {
				id: "863cf0b7-3ae8-4e77-8067-b9bd5b1f162e",
				name: "Bryan Cranston",
				codename: "bryan_cranston",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:11.6294243Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Bryan",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Cranston",
				},
			},
		},
		{
			system: {
				id: "97468922-e32c-40ce-ad75-8ede3edd45d7",
				name: "Cate Blanchett",
				codename: "cate_blanchett",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:14.6089072Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Cate",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Blanchett",
				},
			},
		},
		{
			system: {
				id: "831a6311-5e6a-40ee-bb2e-a1a51439b1e1",
				name: "Chadwick Boseman",
				codename: "chadwick_boseman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:12.1866334Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Chadwick",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Boseman",
				},
			},
		},
		{
			system: {
				id: "8b6a70c2-cc79-40e1-a01a-fa5c6563d947",
				name: "Charlize Theron",
				codename: "charlize_theron",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:28.8990017Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Charlize",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Theron",
				},
			},
		},
		{
			system: {
				id: "7a6f289c-3c2f-4b8d-a66e-f7361e8a2a6f",
				name: "Chris Evans",
				codename: "chris_evans",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:20.9296898Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Chris",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Evans",
				},
			},
		},
		{
			system: {
				id: "921c1a57-2c05-4fa6-a876-7c3b799d3f1b",
				name: "Chris Hemsworth",
				codename: "chris_hemsworth",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:00.457889Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Chris",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Hemsworth",
				},
			},
		},
		{
			system: {
				id: "2630c0c1-f25a-46df-9dd2-f258ff0d3c60",
				name: "Christian Bale",
				codename: "christian_bale",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:23.6060976Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Christian",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Bale",
				},
			},
		},
		{
			system: {
				id: "1fcb9a45-ea77-47ed-9348-5bfba31e9278",
				name: "Christoph Waltz",
				codename: "christoph_waltz",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:57.7940706Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Christoph",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Waltz",
				},
			},
		},
		{
			system: {
				id: "23c90ad1-6963-4c24-b7eb-6967967bd448",
				name: "Cillian Murphy",
				codename: "cillian_murphy",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:48.9787224Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Cillian",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Murphy",
				},
			},
		},
		{
			system: {
				id: "7ea5e2a4-7715-47eb-9f54-55d3860289ed",
				name: "Colin Firth",
				codename: "colin_firth",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:52.3614325Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Colin",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Firth",
				},
			},
		},
		{
			system: {
				id: "a8c19b2a-3f5c-4a1d-9cc8-1a06d83ab301",
				name: "Daniel Craig",
				codename: "daniel_craig",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:18.8005459Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Daniel",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Craig",
				},
			},
		},
		{
			system: {
				id: "7f985920-fed5-4acc-98b2-044bae9bed69",
				name: "Daniel Day-Lewis",
				codename: "daniel_day_lewis",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:00.8239293Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Daniel",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Day-Lewis",
				},
			},
		},
		{
			system: {
				id: "943f8fd8-91c2-4b87-8fec-98ad4e693697",
				name: "Denzel Washington",
				codename: "denzel_washington",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:17.4317276Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Denzel",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Washington",
				},
			},
		},
		{
			system: {
				id: "41b167f9-79ef-4e48-ab01-8cd10f7303af",
				name: "Dwayne Johnson",
				codename: "dwayne_johnson",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:42.3374184Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Dwayne",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Johnson",
				},
			},
		},
		{
			system: {
				id: "ebc99a0d-d44b-4599-a01a-2dfba273a531",
				name: "Eddie Redmayne",
				codename: "eddie_redmayne",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:55.5692481Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Eddie",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Redmayne",
				},
			},
		},
		{
			system: {
				id: "952090fe-5409-49ae-9f0d-238afecab0ab",
				name: "Emily Blunt",
				codename: "emily_blunt",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:49.7782012Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Emily",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Blunt",
				},
			},
		},
		{
			system: {
				id: "1621e70c-99be-455c-b93c-46f68eab6158",
				name: "Emma Stone",
				codename: "emma_stone",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:01.4684966Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Emma",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Stone",
				},
			},
		},
		{
			system: {
				id: "d19f1d6c-52b8-4bf3-8fbc-b019431d3eb1",
				name: "Emma Thompson",
				codename: "emma_thompson",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:58.8051847Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Emma",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Thompson",
				},
			},
		},
		{
			system: {
				id: "5db2ea89-5fb8-4187-9d7c-5389df88b248",
				name: "Ethan Hawke",
				codename: "ethan_hawke",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:08.7084469Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Ethan",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Hawke",
				},
			},
		},
		{
			system: {
				id: "b5640463-7a4c-46c0-8b08-b3c2c0a3f90f",
				name: "Felicity Jones",
				codename: "felicity_jones",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:56.4897287Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Felicity",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Jones",
				},
			},
		},
		{
			system: {
				id: "14622687-19bd-4362-90b3-de3898f7aa6d",
				name: "Florence Pugh",
				codename: "florence_pugh",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:03.2222014Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Florence",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Pugh",
				},
			},
		},
		{
			system: {
				id: "81b0c4cf-37dc-476a-ab0b-d4b2ed8ebbf2",
				name: "Forrest Gump",
				codename: "forrest_gump",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:22.6154672Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Forrest Gump",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 142,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>The story of Forrest Gump, a man with a low IQ but good heart, who unwittingly influences several historical events in 20th century America while longing for his childhood sweetheart Jenny.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "1994-07-06T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Drama",
							codename: "drama",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "forrest-gump",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Winner of 6 Academy Awards including Best Picture, Forrest Gump is a beloved American classic starring Tom Hanks.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["tom_hanks"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "b5365930-21db-4440-abfe-65735f9dac2a",
				name: "Gal Gadot",
				codename: "gal_gadot",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:59.0827865Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Gal",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Gadot",
				},
			},
		},
		{
			system: {
				id: "55b225d8-9d62-4306-9a8f-16feea53a3ac",
				name: "Gary Oldman",
				codename: "gary_oldman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:57.9327818Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Gary",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Oldman",
				},
			},
		},
		{
			system: {
				id: "e777df88-4411-4831-b660-c8d40f776234",
				name: "George Clooney",
				codename: "george_clooney",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:41.4431549Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "George",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Clooney",
				},
			},
		},
		{
			system: {
				id: "9540ec1a-8e48-4036-a435-41defd8589e7",
				name: "Gladiator",
				codename: "gladiator",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:35.2485442Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Gladiator",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 155,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>A former Roman general is betrayed by the emperor's corrupt son, loses everything dear to him, and is forced to become a gladiator. He must use his arena popularity to seek revenge against the tyrannical emperor.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2000-05-05T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Action",
							codename: "action",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "gladiator",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Ridley Scott's Gladiator won 5 Academy Awards including Best Picture, with Russell Crowe delivering an iconic performance.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["russell_crowe"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "c329dea2-e6e4-4985-9ab1-2ec2db8b021b",
				name: "Halle Berry",
				codename: "halle_berry",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:08.1011475Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Halle",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Berry",
				},
			},
		},
		{
			system: {
				id: "af27004b-150d-44d5-992d-7f1200be93e9",
				name: "Harrison Ford",
				codename: "harrison_ford",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:44.5871489Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Harrison",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Ford",
				},
			},
		},
		{
			system: {
				id: "dcc060dc-ce0e-4b1f-af45-c3ef82a90422",
				name: "Helen Mirren",
				codename: "helen_mirren",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:59.1375839Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Helen",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Mirren",
				},
			},
		},
		{
			system: {
				id: "f8543414-e7c2-4598-944b-b80b4b663642",
				name: "Hugh Jackman",
				codename: "hugh_jackman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:11.3590593Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Hugh",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Jackman",
				},
			},
		},
		{
			system: {
				id: "96c9d600-a2b3-4339-b792-112629276dba",
				name: "Ian McKellen",
				codename: "ian_mckellen",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:59.7130962Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Ian",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "McKellen",
				},
			},
		},
		{
			system: {
				id: "ff4bd7e5-40a7-4a0d-bb25-769b414bfdec",
				name: "Idris Elba",
				codename: "idris_elba",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:51.9478946Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Idris",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Elba",
				},
			},
		},
		{
			system: {
				id: "23b4a456-9d2a-4e47-915d-589e41b7329b",
				name: "Inception",
				codename: "inception",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:44.4838819Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Inception",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 148,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>A skilled thief who steals secrets from within people's dreams is given a chance to have his criminal record erased if he can plant an idea into a target's subconscious — a process known as inception.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2010-07-16T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Action",
							codename: "action",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "inception",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Christopher Nolan's mind-bending sci-fi thriller Inception won 4 Academy Awards and is celebrated for its innovative storytelling.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["leonardo_dicaprio", "marion_cotillard"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "e1c9dde8-97dd-4604-8acc-bca0421d8e04",
				name: "Jake Gyllenhaal",
				codename: "jake_gyllenhaal",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:14.2302861Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jake",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Gyllenhaal",
				},
			},
		},
		{
			system: {
				id: "26ddb3e5-46d3-451f-9774-bd68fe604c12",
				name: "James McAvoy",
				codename: "james_mcavoy",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:46.328842Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "James",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "McAvoy",
				},
			},
		},
		{
			system: {
				id: "7427309c-b84a-4c47-9a51-44b3e259b46d",
				name: "Jamie Foxx",
				codename: "jamie_foxx",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:53.2123098Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jamie",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Foxx",
				},
			},
		},
		{
			system: {
				id: "2a5142ec-c56b-44d8-bb86-80553d05f53e",
				name: "Javier Bardem",
				codename: "javier_bardem",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:53.6413359Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Javier",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Bardem",
				},
			},
		},
		{
			system: {
				id: "caad3465-f88c-43db-8d24-f32331c2ac8e",
				name: "Jeff Bridges",
				codename: "jeff_bridges",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:58.5625601Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jeff",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Bridges",
				},
			},
		},
		{
			system: {
				id: "b96c6cbc-fd7d-4a13-9a9a-52fdd425a27a",
				name: "Jennifer Aniston",
				codename: "jennifer_aniston",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:40.2064454Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jennifer",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Aniston",
				},
			},
		},
		{
			system: {
				id: "6a8461ab-6948-4f91-93d1-5b36aaebd3ee",
				name: "Jennifer Lawrence",
				codename: "jennifer_lawrence",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:22.8329501Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jennifer",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Lawrence",
				},
			},
		},
		{
			system: {
				id: "d87ce611-4f91-451e-8fa2-24f0922ba71c",
				name: "Jeremy Renner",
				codename: "jeremy_renner",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:55.7508643Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jeremy",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Renner",
				},
			},
		},
		{
			system: {
				id: "35aba8b4-289b-42aa-82fe-29842ebbfc88",
				name: "Jessica Chastain",
				codename: "jessica_chastain",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:19.9987106Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Jessica",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Chastain",
				},
			},
		},
		{
			system: {
				id: "90e414bd-16f4-4644-8fdd-0c8553396b72",
				name: "Joaquin Phoenix",
				codename: "joaquin_phoenix",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:29.7797132Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Joaquin",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Phoenix",
				},
			},
		},
		{
			system: {
				id: "f52c5bb9-7078-44ee-9bcd-404b8df000a5",
				name: "John David Washington",
				codename: "john_david_washington",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:06.4726897Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "John David",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Washington",
				},
			},
		},
		{
			system: {
				id: "423efdd9-8624-4be1-9fa8-072ff75fed62",
				name: "Joker",
				codename: "joker",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:48.5786297Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Joker",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 122,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>Arthur Fleck, a failed stand-up comedian and part-time clown, is disregarded and mistreated by society. As he descends into madness, he adopts the alter ego of the Joker and becomes the catalyst for chaos in Gotham City.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2019-10-04T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Drama",
							codename: "drama",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "joker",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Joaquin Phoenix won the Academy Award for Best Actor for his transformative portrayal of Arthur Fleck in Todd Phillips' Joker.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["joaquin_phoenix"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "9430c217-39d8-4ad3-91aa-2674acd981a2",
				name: "Judi Dench",
				codename: "judi_dench",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:50.2320048Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Judi",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Dench",
				},
			},
		},
		{
			system: {
				id: "d468218a-e7c8-44cc-84d3-acb37e9dc9ee",
				name: "Julia Roberts",
				codename: "julia_roberts",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:18.3193199Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Julia",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Roberts",
				},
			},
		},
		{
			system: {
				id: "7296fa14-b4d8-4585-8347-ebfe70b798ec",
				name: "Julianne Moore",
				codename: "julianne_moore",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:02.956359Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Julianne",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Moore",
				},
			},
		},
		{
			system: {
				id: "e90e44e2-91f0-4203-857f-fd3faafd025d",
				name: "Kate Winslet",
				codename: "kate_winslet",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:05.6830624Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Kate",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Winslet",
				},
			},
		},
		{
			system: {
				id: "d92f4584-34e9-40c5-baba-ca5d0fdd0b9f",
				name: "Keanu Reeves",
				codename: "keanu_reeves",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:08.9297582Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Keanu",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Reeves",
				},
			},
		},
		{
			system: {
				id: "d4e90b88-679d-4d99-8159-cc0f89228b59",
				name: "Keira Knightley",
				codename: "keira_knightley",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:53.277714Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Keira",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Knightley",
				},
			},
		},
		{
			system: {
				id: "691f96df-d9c3-4d69-95d8-eeb0eb1c65f6",
				name: "La La Land",
				codename: "la_la_land",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:25:30.7299534Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "La La Land",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 128,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>A jazz musician and an aspiring actress fall in love while each pursuing their dreams in Los Angeles. A modern musical celebrating the timeless Hollywood tradition of dreamers and lovers.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2016-12-09T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Drama",
							codename: "drama",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "la-la-land",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Damien Chazelle's La La Land won 6 Academy Awards and revived the Hollywood musical genre.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["ryan_gosling", "emma_stone"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "62de95fa-4468-405a-bf0b-b0b791bdf9ce",
				name: "Leonardo DiCaprio",
				codename: "leonardo_dicaprio",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:14.1998292Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Leonardo",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "DiCaprio",
				},
			},
		},
		{
			system: {
				id: "2c71df49-6390-453f-b2dd-12467406b350",
				name: "Lupita Nyong'o",
				codename: "lupita_nyong_o",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:13.5243957Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Lupita",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Nyong'o",
				},
			},
		},
		{
			system: {
				id: "1aaa04e0-c5e9-4295-bfba-5af17e3be575",
				name: "Mads Mikkelsen",
				codename: "mads_mikkelsen",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:09.6094973Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Mads",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Mikkelsen",
				},
			},
		},
		{
			system: {
				id: "736bc909-0049-42d0-9c33-f272f1f15248",
				name: "Mahershala Ali",
				codename: "mahershala_ali",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:08.9792264Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Mahershala",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Ali",
				},
			},
		},
		{
			system: {
				id: "9437d4dd-69d4-4ce3-a57f-64d8a4c1e1bb",
				name: "Margot Robbie",
				codename: "margot_robbie",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:52.4340963Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Margot",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Robbie",
				},
			},
		},
		{
			system: {
				id: "fda6870f-c881-4271-ba2a-2cbf209573c4",
				name: "Marion Cotillard",
				codename: "marion_cotillard",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:54.4864003Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Marion",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Cotillard",
				},
			},
		},
		{
			system: {
				id: "aee262cf-866c-4d5a-8eb3-889457b2151c",
				name: "Matt Damon",
				codename: "matt_damon",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:02.2760641Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Matt",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Damon",
				},
			},
		},
		{
			system: {
				id: "1c8eba11-646b-4f80-bedf-e7d23a665966",
				name: "Meryl Streep",
				codename: "meryl_streep",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:13.7111314Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Meryl",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Streep",
				},
			},
		},
		{
			system: {
				id: "973aa0fa-311a-45fd-9adf-0ffc3c7df75a",
				name: "Michael B. Jordan",
				codename: "michael_b__jordan",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:47.5846647Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Michael B.",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Jordan",
				},
			},
		},
		{
			system: {
				id: "f801888e-147d-4509-ad86-252f7918ab7b",
				name: "Michael Fassbender",
				codename: "michael_fassbender",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:16.7654414Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Michael",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Fassbender",
				},
			},
		},
		{
			system: {
				id: "71c28bd9-3fe4-47fb-af29-9c882fb0b623",
				name: "Michelle Yeoh",
				codename: "michelle_yeoh",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:51.6922888Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Michelle",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Yeoh",
				},
			},
		},
		{
			system: {
				id: "6dddc4e0-1425-44b5-8b4c-00a9690a2f90",
				name: "Morgan Freeman",
				codename: "morgan_freeman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:21.5555586Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Morgan",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Freeman",
				},
			},
		},
		{
			system: {
				id: "45d594c5-b251-4d3d-864d-c78a3d2c285b",
				name: "Movie with empty rich text",
				codename: "movie_with_empty_rich_text",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-10T10:23:44.1265574Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "Movie with empty rich text",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 0,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p><br></p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "no",
							codename: "no",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2026-04-09T22:00:00Z",
					display_timezone: "Europe/Budapest",
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Drama",
							codename: "drama",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "movie-with-empty-rich-text",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["joker"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
		{
			system: {
				id: "218a80d2-6787-4086-9728-5c06170d92ef",
				name: "Naomi Watts",
				codename: "naomi_watts",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:55.0766398Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Naomi",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Watts",
				},
			},
		},
		{
			system: {
				id: "090807a7-c5a1-4d42-8987-d820c06bb6a9",
				name: "Natalie Portman",
				codename: "natalie_portman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:26.8476502Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Natalie",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Portman",
				},
			},
		},
		{
			system: {
				id: "08271858-e58e-401b-9aa9-c13a86a54fdb",
				name: "Nicole Kidman",
				codename: "nicole_kidman",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:31.0302744Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Nicole",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Kidman",
				},
			},
		},
		{
			system: {
				id: "0b83b3dc-1849-4a8b-8e7f-222b581a0fff",
				name: "Nora Lum",
				codename: "nora_lum",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:07.7026459Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Nora",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Lum",
				},
			},
		},
		{
			system: {
				id: "f51a15db-f5f5-4c2c-98b3-1d3918bd672f",
				name: "Oscar Isaac",
				codename: "oscar_isaac",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:07.5328891Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Oscar",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Isaac",
				},
			},
		},
		{
			system: {
				id: "e2bc46cd-a7ea-4cde-8d4e-b56e30708bca",
				name: "Pedro Pascal",
				codename: "pedro_pascal",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:04.4430733Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Pedro",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Pascal",
				},
			},
		},
		{
			system: {
				id: "e285cba4-294f-44a5-b76e-088cf89371be",
				name: "Penélope Cruz",
				codename: "penelope_cruz",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:05.4809267Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Penélope",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Cruz",
				},
			},
		},
		{
			system: {
				id: "76a5c1fc-46bc-4274-8a19-07e74a0c801e",
				name: "Rachel McAdams",
				codename: "rachel_mcadams",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:56.9474259Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Rachel",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "McAdams",
				},
			},
		},
		{
			system: {
				id: "03ef6927-eb79-4be2-85fa-44a9f5d01ae8",
				name: "Ralph Fiennes",
				codename: "ralph_fiennes",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:50.9985727Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Ralph",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Fiennes",
				},
			},
		},
		{
			system: {
				id: "e5b44b09-572e-4768-9856-9f44e5df70aa",
				name: "Reese Witherspoon",
				codename: "reese_witherspoon",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:10.1223156Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Reese",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Witherspoon",
				},
			},
		},
		{
			system: {
				id: "fbb9eb43-1405-4884-94bb-6ef230b87a65",
				name: "Regina King",
				codename: "regina_king",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:09.8875628Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Regina",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "King",
				},
			},
		},
		{
			system: {
				id: "46663b41-3619-484e-a1f9-6e4cc9ca3ab0",
				name: "Robert De Niro",
				codename: "robert_de_niro",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:19.593274Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Robert",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "De Niro",
				},
			},
		},
		{
			system: {
				id: "bbc14c55-9d5b-4c75-a968-6e17799987a7",
				name: "Robert Downey Jr.",
				codename: "robert_downey_jr_",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:45.6740229Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Robert",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Downey Jr.",
				},
			},
		},
		{
			system: {
				id: "4c0f7928-a8c1-4b70-b2bd-62dc85722570",
				name: "Rooney Mara",
				codename: "rooney_mara",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:23:54.64466Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Rooney",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Mara",
				},
			},
		},
		{
			system: {
				id: "906326c7-9d66-432a-b49d-2728f48e3825",
				name: "Russell Crowe",
				codename: "russell_crowe",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:56.2128676Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Russell",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Crowe",
				},
			},
		},
		{
			system: {
				id: "dee9a365-71ee-4f1f-a430-d98f93bfe817",
				name: "Ryan Gosling",
				codename: "ryan_gosling",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:04.4007354Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Ryan",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Gosling",
				},
			},
		},
		{
			system: {
				id: "94baa269-30cd-42b0-b54b-7be65b61fe0c",
				name: "Salma Hayek",
				codename: "salma_hayek",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:24:04.2441153Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Salma",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Hayek",
				},
			},
		},
		{
			system: {
				id: "4cc3ccd6-8fc4-403f-a816-9ed97d302f82",
				name: "Samuel L. Jackson",
				codename: "samuel_l__jackson",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:53.7929068Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Samuel L.",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Jackson",
				},
			},
		},
		{
			system: {
				id: "5409a321-144d-44b5-847e-4cfdab10a68b",
				name: "Sandra Bullock",
				codename: "sandra_bullock",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:24.8943758Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Sandra",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Bullock",
				},
			},
		},
		{
			system: {
				id: "cb58900c-56fa-4331-a2d2-89d708c580ad",
				name: "Saoirse Ronan",
				codename: "saoirse_ronan",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:21:50.4309368Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Saoirse",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Ronan",
				},
			},
		},
		{
			system: {
				id: "70c23859-845e-40d6-86f7-2c1865ff828d",
				name: "Scarlett Johansson",
				codename: "scarlett_johansson",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:20:20.2541643Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Scarlett",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Johansson",
				},
			},
		},
		{
			system: {
				id: "3b8c25d3-fabe-4451-b0c1-c5b95ba15579",
				name: "Sigourney Weaver",
				codename: "sigourney_weaver",
				language: "default",
				type: "star",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:22:57.743072Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				firstname: {
					type: "text",
					name: "Firstname",
					value: "Sigourney",
				},
				lastname: {
					type: "text",
					name: "Lastname",
					value: "Weaver",
				},
			},
		},
		{
			system: {
				id: "21586dc9-9c04-4c9e-a9e4-83b8cd65baef",
				name: "The Dark Knight",
				codename: "the_dark_knight",
				language: "default",
				type: "movie",
				collection: "default",
				sitemap_locations: [],
				last_modified: "2026-04-07T10:36:42.4587906Z",
				workflow: "default",
				workflow_step: "published",
			},
			elements: {
				title: {
					type: "text",
					name: "Title",
					value: "The Dark Knight",
				},
				length_in_minutes: {
					type: "number",
					name: "Length in minutes",
					value: 152,
				},
				description: {
					type: "rich_text",
					name: "Description",
					images: {},
					links: {},
					modular_content: [],
					value: "<p>Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, he sets out to dismantle the remaining criminal organizations that plague Gotham City. But the emergence of the Joker creates chaos.</p>",
				},
				is_blockbuster: {
					type: "multiple_choice",
					name: "Is blockbuster",
					value: [
						{
							name: "yes",
							codename: "yes",
						},
					],
				},
				release_date: {
					type: "date_time",
					name: "Release date",
					value: "2008-07-18T00:00:00Z",
					display_timezone: null,
				},
				cover: {
					type: "asset",
					name: "Cover",
					value: [
						{
							name: "The_Dark_Knight_(2008_film).jpg",
							description: null,
							type: "image/jpeg",
							size: 52188,
							url: "https://assets-eu-01.kc-usercontent.com:443/6bdd84fc-f71e-01a0-0ba6-79ce07af7f9b/1ee1e759-4af3-4f0a-acfc-b61a88c1eafe/The_Dark_Knight_%282008_film%29.jpg",
							width: 259,
							height: 383,
							renditions: {},
						},
					],
				},
				category: {
					type: "taxonomy",
					name: "Category",
					taxonomy_group: "movie_type",
					value: [
						{
							name: "Action",
							codename: "action",
						},
					],
				},
				url: {
					type: "url_slug",
					name: "Url",
					value: "the-dark-knight",
				},
				metadata__metadata_description: {
					type: "text",
					name: "Metadata description",
					value: "Christopher Nolan's The Dark Knight is widely regarded as one of the greatest superhero films ever made.",
				},
				cast: {
					type: "modular_content",
					name: "Cast",
					value: ["christian_bale", "gary_oldman"],
				},
				custom: {
					type: "custom",
					name: "Custom",
					value: null,
				},
			},
		},
	],
	modular_content: {},
} satisfies ItemsFeedPayload<DeliveryClientSchema>;
