on:
  release:
    types: [published]

permissions:
  # Required for OIDC publishing
  id-token: write
  contents: read

env:
    INTEGRATION_ENVIRONMENT_ID: ${{ secrets.INTEGRATION_ENVIRONMENT_ID }}

name: publish-to-npm
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      - run: pnpm run test

      - run: pnpm publish --access=public --no-git-checks
        if: ${{!github.event.release.prerelease}}
      - run: pnpm publish --tag prerelease --access=public --no-git-checks
        if: ${{github.event.release.prerelease}}
